from django.urls import path

from socials.views import (
    ConnectUrlView,
    OAuthCallbackView,
    PageListView,
    PageConnectView,
    PageDisconnectView,
    PageProfileImportView,
    InstagramConnectUrlView,
    InstagramRedirectBridgeView,
    BoostAdvisorView,
    AdAccountListView,
    BoostListCreateView,
    BoostActionView,
    InstagramOAuthCallbackView,
    PostDetailView,
    PostRetryView,
    PublishPostView,
    WhatsAppConnectView,
)

urlpatterns = [
    path('posts/', PublishPostView.as_view(), name='socials_publish_post'),
    path('posts/<int:post_id>/', PostDetailView.as_view(), name='socials_post_detail'),
    path('posts/<int:post_id>/retry/', PostRetryView.as_view(), name='socials_post_retry'),
    path('connect-url/', ConnectUrlView.as_view(), name='socials_connect_url'),
    path('boost-advisor/', BoostAdvisorView.as_view(), name='socials_boost_advisor'),
    path('ad-accounts/', AdAccountListView.as_view(), name='socials_ad_accounts'),
    path('boosts/', BoostListCreateView.as_view(), name='socials_boosts'),
    path('boosts/<int:boost_id>/<str:action>/', BoostActionView.as_view(), name='socials_boost_action'),
    path('instagram/connect-url/', InstagramConnectUrlView.as_view(), name='socials_instagram_connect_url'),
    path('instagram/redirect/', InstagramRedirectBridgeView.as_view(), name='socials_instagram_redirect'),
    path('instagram/oauth/callback/', InstagramOAuthCallbackView.as_view(), name='socials_instagram_oauth_callback'),
    path('oauth/callback/', OAuthCallbackView.as_view(), name='socials_oauth_callback'),
    path('whatsapp/connect/', WhatsAppConnectView.as_view(), name='socials_whatsapp_connect'),
    path('pages/', PageListView.as_view(), name='socials_pages'),
    path('pages/<str:page_id>/connect/', PageConnectView.as_view(), name='socials_page_connect'),
    path('pages/import-profile/', PageProfileImportView.as_view(), name='socials_page_import_profile'),
    path('pages/<str:page_id>/disconnect/', PageDisconnectView.as_view(), name='socials_page_disconnect'),
]
