# Generated by Django 5.0.14 on 2026-08-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_engagement_refresh_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedpage',
            name='connection_type',
            field=models.CharField(choices=[('facebook_page', 'Facebook Page'), ('instagram_direct', 'Instagram (direct login)')], default='facebook_page', max_length=20),
        ),
    ]
