# Generated by Django 5.0.14 on 2026-08-21 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_product_item_type'),
        ('socials', '0005_instagram_token_refresh_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_account_id', models.CharField(max_length=64)),
                ('campaign_id', models.CharField(blank=True, default='', max_length=64)),
                ('adset_id', models.CharField(blank=True, default='', max_length=64)),
                ('ad_id', models.CharField(blank=True, default='', max_length=64)),
                ('daily_budget', models.IntegerField()),
                ('days', models.IntegerField(default=5)),
                ('targeting', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('status_note', models.CharField(blank=True, default='', max_length=255)),
                ('insights', models.JSONField(blank=True, default=dict)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='core.socialmediapost')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
