# Generated by Django 5.0.14 on 2026-09-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0007_boost_refresh_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedpage',
            name='connection_type',
            field=models.CharField(choices=[('facebook_page', 'Facebook Page'), ('instagram_direct', 'Instagram (direct login)'), ('whatsapp', 'WhatsApp Business')], default='facebook_page', max_length=20),
        ),
    ]
