# Generated by Django 5.0.14 on 2026-09-04 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_tenant_subscription'),
        ('socials', '0008_alter_connectedpage_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaconnection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_connections', to='core.tenant'),
        ),
        migrations.AddConstraint(
            model_name='metaconnection',
            constraint=models.UniqueConstraint(fields=('tenant', 'fb_user_id'), name='unique_connection_identity'),
        ),
    ]
