# Generated by Django 5.0.14 on 2026-08-18 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_add_product_variant'),
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('platform_user_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('profile_pic_url', models.URLField(blank=True, default='', max_length=500)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_customers', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('waiting_business', 'Waiting for business'), ('waiting_customer', 'Waiting for customer'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('unread_count', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=140)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='socials.connectedpage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.tenant')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='inbox.customer')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3)),
                ('text', models.TextField(blank=True, default='')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('platform_message_id', models.CharField(max_length=255, unique=True)),
                ('sent_at', models.DateTimeField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.conversation')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant', 'platform', 'platform_user_id'), name='unique_customer_identity'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('page', 'customer'), name='unique_page_customer_thread'),
        ),
    ]
