# Generated by Django 5.0.14 on 2026-08-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_conversation_ai_paused_message_sent_by_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.CharField(choices=[('dm', 'Direct message'), ('comment', 'Post comment')], default='dm', max_length=10),
        ),
    ]
