# Generated by Django 5.0.14 on 2026-08-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_message_metadata_message_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
