# Generated by Django 5.0.14 on 2026-08-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_conversation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='sentiment',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
