# Generated by Django 5.0.14 on 2026-08-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_customer_email_customer_location_customer_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='followup_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='order_intent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
