# Generated by Django 5.0.14 on 2026-01-15 10:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productimage_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.Product.product_image_path),
        ),
        migrations.AddField(
            model_name='productimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ProductImage.product_gallery_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.Product.product_image_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=core.models.ProductImage.product_gallery_path),
        ),
    ]
