# Generated by Django 5.0.14 on 2026-01-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
