# Generated by Django 5.0.14 on 2026-01-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vibe_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
