# Generated by Django 5.0.14 on 2026-01-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_vibe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_by_size',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
