# Generated by Django 5.0.14 on 2026-01-19 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_customer_email_order_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='True for system-wide template themes')),
                ('is_ai_generated', models.BooleanField(default=False, help_text='True for AI-generated themes from logo analysis')),
                ('primary', models.CharField(default='#8A2BE2', max_length=50)),
                ('accent', models.CharField(default='#a855f7', max_length=50)),
                ('background', models.CharField(default='#f5f3f8', max_length=50)),
                ('surface', models.CharField(default='#ffffff', max_length=50)),
                ('text', models.CharField(default='#1a1a2e', max_length=50)),
                ('text_secondary', models.CharField(default='#6b7280', max_length=50)),
                ('border', models.CharField(default='#e5e7eb', max_length=50)),
                ('card_bg', models.CharField(default='#ffffff', max_length=50)),
                ('button_bg', models.CharField(default='#8A2BE2', max_length=50)),
                ('button_text', models.CharField(default='#ffffff', max_length=50)),
                ('gradient', models.CharField(default='linear-gradient(135deg, #8A2BE2 0%, #a855f7 100%)', max_length=255)),
                ('text_gradient', models.CharField(default='linear-gradient(135deg, #8A2BE2, #E040FB)', max_length=255)),
                ('brand_style', models.CharField(blank=True, max_length=100)),
                ('brand_keywords', models.JSONField(blank=True, default=list)),
                ('recommendation_reason', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null for default themes, set for vendor-specific themes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='core.tenant')),
            ],
            options={
                'ordering': ['-is_default', '-is_ai_generated', 'created_at'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
    ]
