# Generated by Django migration script

from django.db import migrations


def seed_default_themes(apps, schema_editor):
    """Seed the 3 default themes."""
    Theme = apps.get_model('core', 'Theme')
    
    # Skip if themes already exist
    if Theme.objects.filter(is_default=True).exists():
        return
    
    default_themes = [
        {
            'name': 'Neon Vibe',
            'slug': 'neon-vibe',
            'description': 'Bold and vibrant, perfect for social sellers.',
            'is_default': True,
            'is_ai_generated': False,
            'primary': '#8A2BE2',
            'accent': '#a855f7',
            'background': '#f5f3f8',
            'surface': '#ffffff',
            'text': '#1a1a2e',
            'text_secondary': '#6e6e80',
            'border': '#e5e5f0',
            'card_bg': '#ffffff',
            'button_bg': '#8A2BE2',
            'button_text': '#ffffff',
            'gradient': 'linear-gradient(135deg, #8A2BE2 0%, #a855f7 100%)',
            'text_gradient': 'linear-gradient(135deg, #8A2BE2, #E040FB)',
        },
        {
            'name': 'Minimal',
            'slug': 'minimal',
            'description': 'Clean and professional for a modern look.',
            'is_default': True,
            'is_ai_generated': False,
            'primary': '#18181b',
            'accent': '#3f3f46',
            'background': '#fafafa',
            'surface': '#ffffff',
            'text': '#18181b',
            'text_secondary': '#71717a',
            'border': '#e4e4e7',
            'card_bg': '#ffffff',
            'button_bg': '#18181b',
            'button_text': '#ffffff',
            'gradient': 'linear-gradient(135deg, #18181b 0%, #3f3f46 100%)',
            'text_gradient': 'linear-gradient(135deg, #27272a, #52525b)',
        },
        {
            'name': 'Warm & Cozy',
            'slug': 'warm-cozy',
            'description': 'Inviting and organic for a handmade feel.',
            'is_default': True,
            'is_ai_generated': False,
            'primary': '#d97706',
            'accent': '#f59e0b',
            'background': '#fffbeb',
            'surface': '#ffffff',
            'text': '#451a03',
            'text_secondary': '#78350f',
            'border': '#fde68a',
            'card_bg': '#ffffff',
            'button_bg': '#d97706',
            'button_text': '#ffffff',
            'gradient': 'linear-gradient(135deg, #d97706 0%, #f59e0b 100%)',
            'text_gradient': 'linear-gradient(135deg, #d97706, #fbbf24)',
        },
    ]
    
    for theme_data in default_themes:
        Theme.objects.create(**theme_data)


def remove_default_themes(apps, schema_editor):
    """Remove seeded themes on rollback."""
    Theme = apps.get_model('core', 'Theme')
    Theme.objects.filter(is_default=True, slug__in=['neon-vibe', 'minimal', 'warm-cozy']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_theme_model'),
    ]

    operations = [
        migrations.RunPython(seed_default_themes, remove_default_themes),
    ]
