# Generated by Django 5.0.14 on 2026-01-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_default_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weather_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
