# Generated by Django 5.0.14 on 2026-01-19 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_weather_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI')], max_length=20)),
                ('operation_type', models.CharField(choices=[('product_analysis', 'Product Image Analysis'), ('logo_analysis', 'Logo Analysis'), ('description_generation', 'Description Generation'), ('tag_generation', 'Tag Generation')], max_length=50)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage', to='core.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='core_aitoke_tenant__1a2c91_idx'), models.Index(fields=['user', '-created_at'], name='core_aitoke_user_id_c57d40_idx'), models.Index(fields=['product'], name='core_aitoke_product_6c0e04_idx'), models.Index(fields=['ai_provider'], name='core_aitoke_ai_prov_869ea4_idx'), models.Index(fields=['operation_type'], name='core_aitoke_operati_a42216_idx')],
            },
        ),
    ]
