# Generated by Django 5.0.14 on 2026-08-18 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/social_posts/'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='core.product'),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
