# Generated by Django 5.0.14 on 2026-08-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_socialmediapost_image_socialmediapost_scheduled_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='post_format',
            field=models.CharField(choices=[('feed', 'Feed'), ('story', 'Story')], default='feed', max_length=10),
        ),
    ]
