# Generated by Django 5.0.14 on 2026-08-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_backfill_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Source info and collected order details (e.g. chat bot fields)'),
        ),
    ]
