# Generated by Django 5.0.14 on 2026-08-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_orderitem_color_orderitem_size_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delta', models.IntegerField()),
                ('resulting_stock', models.IntegerField()),
                ('reason', models.CharField(choices=[('initial', 'Initial stock'), ('manual', 'Manual adjustment'), ('order', 'Order placed'), ('chat_order', 'Chat bot order'), ('online_order', 'Online order')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
