# Generated by Django 5.0.14 on 2026-08-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_stockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitokenusage',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('claude', 'Anthropic Claude'), ('openai', 'OpenAI'), ('none', 'Failed (no provider)')], max_length=20),
        ),
    ]
