# Generated by Django 5.0.14 on 2026-08-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_aitokenusage_ai_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('physical', 'Physical product'), ('service', 'Service')], default='physical', max_length=10),
        ),
    ]
