# Generated by Django 5.0.14 on 2026-09-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_product_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='subscription',
        ),
    ]
